title:            Components Programming
tagline:          Efficient programming using Components.
description: > # this means to ignore newlines until "baseurl:"
  My name is Fernando Pelliccioni. I am a computer programmer for over 20 years.
  I’ve been working in several industries for more than 16 years, from telecom to game industry.
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://fpelliccioni.github.io" # the base hostname & protocol for your site
#twitter_username: ferpelliccioni
#github_username:  fpelliccioni
canonical: http://jekyll.gtat.me

# Owner/author information
owner:
  name:           Fernando Pelliccioni
  # avatar:         avatar.png
  avatar:         avatar.jpg
  bio:            "Nature & Programming"
  email:          fpelliccioni@gmail.com
  twitter:        ferpelliccioni
  github:         fpelliccioni
  disqus:         componentsprogramming
  location:       "Castelar, Buenos Aires, Argentina"
  #instagram:      ctrunsthis
  #dribbble:       coletownsend
  # Plug in your disqus shortname!

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#        
analytics :
  provider : google
  google : 
      tracking_id : 'UA-55291427-1'
  getclicky :
    site_id :


tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
  - title: Github
    url: https://github.com/fpelliccioni/componentsprogramming
    external: true
#  - title: Cole Who?
#    url: http://coletownsend.com
#    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Argentina/Buenos_Aires
future:      true
# highlighter: rouge				#Ruby bases syntax highlighter
highlighter: pygments			#Python bases syntax highlighter
# markdown:    kramdown			#Default
markdown:    redcarpet			#Used by this blog ... http://gastonsanchez.com/blog/opinion/2014/02/16/Mathjax-with-jekyll.html ... to suport Latex

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
