title:            Components Programming
tagline:          Efficient programming using Components.
description: > # this means to ignore newlines until "baseurl:"
  Efficient programming using Components.
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://fpelliccioni.github.io" # the base hostname & protocol for your site
#twitter_username: ferpelliccioni
#github_username:  fpelliccioni
canonical: http://componentsprogramming.com

# Owner/author information
owner:
  name:           Fernando Pelliccioni
  avatar:         avatar.jpg
  bio:            "Programming, Algorithms, Bitcoin"
  email:          fpelliccioni@gmail.com
  twitter:        ferpelliccioni
  github:         fpelliccioni
  disqus:         componentsprogramming
  location:       "Castelar, Buenos Aires, Argentina"
  #instagram:      ctrunsthis
  #dribbble:       coletownsend
  # Plug in your disqus shortname!

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#        
analytics :
  provider : google
  google : 
      tracking_id : 'UA-55291427-1'
# getclicky :
# site_id :


tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

defaults:
  -
    scope:
      path: ""
    values:
      lang: en
      layout: default
  -
    scope:
      path: _posts/es
    values:
      lang: es
  -
    scope:
      path: _posts/es/pages
    values:
      type: pages
      desc: "Site personnel traitant essentiellement de programmation en Python, Ruby, TeX, R..."
  -
    scope:
      path: _posts/en/pages
    values:
      type: pages
      desc: "Personnal website mostly about programming in Python, Ruby, TeX, R..."


# # Links to include in top navigation
# # For external links add external: true
# links:
#   - title: About
#     url: /about
#   - title: Github
#     url: https://github.com/fpelliccioni/componentsprogramming
#     external: true
# #  - title: Cole Who?
# #    url: http://coletownsend.com
# #    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Argentina/Buenos_Aires
future:      true
highlighter: rouge				#Ruby bases syntax highlighter
# highlighter: pygments			#Python bases syntax highlighter
markdown:    kramdown			#Default
# markdown:    redcarpet			#Used by this blog ... http://gastonsanchez.com/blog/opinion/2014/02/16/Mathjax-with-jekyll.html ... to suport Latex
# redcarpet:
#   extensions: ["underline"]
#   # extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]



kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
# permalink:   /:categories/:title
permalink: /:title/

include: [".htaccess"]
exclude: ["vendor", "lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]



# webserver_headers:
#   - - Access-Control-Allow-Origin
#     - "*"
#   - - Access-Control-Allow-Methods
#     - GET, OPTIONS, HEAD


webrick:
  headers:
    Access-Control-Allow-Origin: "*"

